services:
  api:
    image: container.cs.vt.edu/dannyb3/policy-safe-prompt-library:latest
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "${PORT}:4000"
    environment:
      - MONGODB_URI=${MONGODB_URI}